### ISSUE TITLE
Potential PII leak

### ISSUE THREAD

**Issue by jamestelfer** [binaryseed/new_relic_absinthe#14]
The default configuration for the middleware publishes the resolver arguments to New Relic, which may include PII. The information could be useful, but it would probably be better to be opt-in to avoid unexpected information leakage to a third party service.

https://github.com/binaryseed/new_relic_absinthe/blob/42e1cdbcfdeeed0fe55115b2a8c3a5b9ecb5d6d7/lib/new_relic/absinthe/middleware.ex#L50

A potential solution could be to make the addition of `args` to the parameters configurable.

What are your thoughts? Are you interested in a PR for this change?

**Comment by sgtpepper43** [comment]
We had this same problem so we forked it and added a config similar to Absinthe Logger's config. We've been sitting on it for a couple of months but I just opened a PR for it today #15

**Comment by jamestelfer** [comment]
I left a comment on the PR; IMO to avoid PII leakage it shouldn't publish this information by default at all, instead making it opt-in.

**Comment by binaryseed** [comment]
Newer agent versions have a config `function_argument_collection_enabled` that I can leverage to determine if we should include the arguments...
